
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/thymeleaf
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false #热部署文件，页面不产生缓存，及时更新
#  resources:
#    chain:
#      strategy:
#        content:
#          enabled: true
#          paths: /**
server:
  port: 8087

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.framk.autocode.dao: DEBUG
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.framk.autocode.entity  # 注意：对应实体类的路径
#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true #大于最大也显示最后一页  小于最小也显示第一页
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check




